package Game;

import javafx.animation.TranslateTransition;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;

import java.util.Random;

public class gameData {
    Random random = new Random();

    public static ImageView getPrincess() {
        return princess;
    }

    private static final ImageView princess = new ImageView(new Image("/Resources/princess.png", true));
    private final double sceneChanger = 10495;

    public gameData(int mode) {
//        princess.setLayoutX(sceneChanger + 5900);
        princess.setLayoutY(328);
        princess.setFitHeight(48);
        princess.setFitWidth(48);
        if (mode == 0 || mode == 1) {  // Easy - 0, Normal - 1 (Difference in gameplay speed)
            GlobalVariables.gameObjects.add(new mediumPlatform(-18, 208));
            GlobalVariables.gameObjects.add(new smallPlatform(287, 252));
            GlobalVariables.gameObjects.add(new greenOrc(730, 275));
            GlobalVariables.gameObjects.add(new Coin(930, 236));
            GlobalVariables.gameObjects.add(new Coin(960, 236));
            GlobalVariables.gameObjects.add(new Coin(990, 236));
            GlobalVariables.gameObjects.add(new bigPlatform(555, 224));
            GlobalVariables.gameObjects.add(new smallPlatform(1176, 182));
            GlobalVariables.gameObjects.add(new greenOrc(1628, 292));
            GlobalVariables.gameObjects.add(new mediumPlatform(1477, 211));
            GlobalVariables.gameObjects.add(new smallPlatform(1816, 204));
            GlobalVariables.gameObjects.add(new coinChest(2124, 239, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new smallPlatform(2096, 242));
            GlobalVariables.gameObjects.add(new greenOrc(2518, 276));
            GlobalVariables.gameObjects.add(new mediumPlatform(2402, 194));
            GlobalVariables.gameObjects.add(new greenOrc(2902, 384));
            GlobalVariables.gameObjects.add(new mediumPlatform(2748, 302));
            GlobalVariables.gameObjects.add(new smallPlatform(3115, 271));
            GlobalVariables.gameObjects.add(new redOrc(3567, 296));
            GlobalVariables.gameObjects.add(new smallPlatform(3431, 230));
            GlobalVariables.gameObjects.add(new weaponChest(3759, 207, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new smallPlatform(3728, 209));
            GlobalVariables.gameObjects.add(new greenOrc(4221, 322));
            GlobalVariables.gameObjects.add(new greenOrc(4378, 322));
            GlobalVariables.gameObjects.add(new Coin(4221+30, 267+12));
            GlobalVariables.gameObjects.add(new Coin(4221+60, 267+12));
            GlobalVariables.gameObjects.add(new Coin(4221+90, 267+12));
            GlobalVariables.gameObjects.add(new bigPlatform(4033, 267));
            GlobalVariables.gameObjects.add(new greenOrc(4823, 311));
            GlobalVariables.gameObjects.add(new mediumPlatform(4657, 230));
            GlobalVariables.gameObjects.add(new greenOrc(5124, 350));
            GlobalVariables.gameObjects.add(new smallPlatform(4983, 284));
            GlobalVariables.gameObjects.add(new greenOrc(5374, 309));
            GlobalVariables.gameObjects.add(new smallPlatform(5233, 244));
            GlobalVariables.gameObjects.add(new smallPlatform(5499, 206));
            GlobalVariables.gameObjects.add(new coinChest(5785, 348, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new smallPlatform(5767, 348));
            GlobalVariables.gameObjects.add(new greenOrc(6216, 364));
            GlobalVariables.gameObjects.add(new redOrc(6443, 364));
            GlobalVariables.gameObjects.add(new Coin(6066+30, 310+12));
            GlobalVariables.gameObjects.add(new Coin(6066+60, 310+12));
            GlobalVariables.gameObjects.add(new Coin(6066+90, 310+12));
            GlobalVariables.gameObjects.add(new bigPlatform(6066, 310));
            GlobalVariables.gameObjects.add(new greenOrc(6723, 317));
            GlobalVariables.gameObjects.add(new weaponChest(6778, 247, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new mediumPlatform(6666, 235));
            GlobalVariables.gameObjects.add(new redOrc(7154, 300));
            GlobalVariables.gameObjects.add(new mediumPlatform(6999, 218));
            GlobalVariables.gameObjects.add(new smallPlatform(7311, 316));
            GlobalVariables.gameObjects.add(new redOrc(7628, 355));
            GlobalVariables.gameObjects.add(new smallPlatform(7544, 289));
            GlobalVariables.gameObjects.add(new redOrc(7974, 331));
            GlobalVariables.gameObjects.add(new mediumPlatform(7808, 249));
            GlobalVariables.gameObjects.add(new TNT(8271, 314));
            GlobalVariables.gameObjects.add(new redOrc(8441, 324));
            GlobalVariables.gameObjects.add(new coinChest(8443, 257, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new redOrc(8576, 324));
            GlobalVariables.gameObjects.add(new Coin(8148+30, 269+12));
            GlobalVariables.gameObjects.add(new Coin(8148+60, 269+12));
            GlobalVariables.gameObjects.add(new Coin(8148+90, 269+12));
            GlobalVariables.gameObjects.add(new Coin(8148+30, 269-18));
            GlobalVariables.gameObjects.add(new Coin(8148+60, 269-18));
            GlobalVariables.gameObjects.add(new Coin(8148+90, 269-18));
            GlobalVariables.gameObjects.add(new bigPlatform(8148, 269));
            GlobalVariables.gameObjects.add(new smallPlatform(8723, 217));
            GlobalVariables.gameObjects.add(new smallPlatform(8957, 284));
            GlobalVariables.gameObjects.add(new mediumPlatform(9377, 272));
            GlobalVariables.gameObjects.add(new redOrc(9831, 314));
            GlobalVariables.gameObjects.add(new smallPlatform(9682, 248));
            GlobalVariables.gameObjects.add(new redOrc(10077, 283));
            GlobalVariables.gameObjects.add(new smallPlatform(9930, 216));
            GlobalVariables.gameObjects.add(new weaponChest(10230, 183, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new smallPlatform(10202, 184));
            GlobalVariables.gameObjects.add(new TNT(10501, 357));
            GlobalVariables.gameObjects.add(new redOrc(10834, 370));
            GlobalVariables.gameObjects.add(new TNT(10926, 357));
            GlobalVariables.gameObjects.add(new Coin(10495+30, 314+12));
            GlobalVariables.gameObjects.add(new Coin(10495+60, 314+12));
            GlobalVariables.gameObjects.add(new Coin(10495+90, 314+12));
            GlobalVariables.gameObjects.add(new Coin(10495+30, 314-18));
            GlobalVariables.gameObjects.add(new Coin(10495+60, 314-18));
            GlobalVariables.gameObjects.add(new Coin(10495+90, 314-18));
            GlobalVariables.gameObjects.add(new bigPlatform(10495, 314));
            GlobalVariables.gameObjects.add(new greenOrc(sceneChanger + 696, 346));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 552, 280));
            GlobalVariables.gameObjects.add(new greenOrc(sceneChanger + 936, 327));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 782, 263));
            GlobalVariables.gameObjects.add(new coinChest(sceneChanger + 1036, 232, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new greenOrc(sceneChanger + 1173, 294));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 1028, 230));
            GlobalVariables.gameObjects.add(new greenOrc(sceneChanger + 1421, 271));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 1279, 204));
            GlobalVariables.gameObjects.add(new greenOrc(sceneChanger + 1673, 238));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 1525, 172));
            GlobalVariables.gameObjects.add(new greenOrc(sceneChanger + 1939, 206));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 1795, 141));
            GlobalVariables.gameObjects.add(new weaponChest(sceneChanger + 1981, 394, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 2196, 461));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 2000, 380));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 2528, 422));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 2328, 341));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 2626, 321));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 3037, 355));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 2882, 290));
            GlobalVariables.gameObjects.add(new TNT(sceneChanger + 3215, 396));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 3135, 343));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 3449, 359));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 3374, 293));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 3803, 325));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 3904, 325));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 4014, 325));
            GlobalVariables.gameObjects.add(new TNT(sceneChanger + 4102, 311));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+30, 269+12));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+60, 269+12));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+90, 269+12));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+30, 269-18));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+60, 269-18));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+90, 269-18));
            GlobalVariables.gameObjects.add(new bigPlatform(sceneChanger + 3650, 269));
            GlobalVariables.gameObjects.add(new weaponChest(sceneChanger + 4262, 298, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 4220, 282));
            GlobalVariables.gameObjects.add(new weaponChest(sceneChanger + 4500, 271, 0));  // test
            GlobalVariables.gameObjects.add(new coinChest(sceneChanger + 4575, 271, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 4530, 256));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 4925, 266));
            //boss lvl
            GlobalVariables.gameObjects.add(new bossOrc(sceneChanger + 5498, 223));
            GlobalVariables.gameObjects.add(new bigPlatform(sceneChanger + 5231, 275));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 5693, 249));
            GlobalVariables.gameObjects.add(new bigPlatform(sceneChanger + 5876, 275));
            GlobalVariables.gameObjects.add(new bigPlatform(sceneChanger + 6500, 260));
        }
        else {  // Hard - 2 (Difference in game objects on the screen)
            GlobalVariables.gameObjects.add(new mediumPlatform(-18, 208));
            GlobalVariables.gameObjects.add(new smallPlatform(287, 252));
            GlobalVariables.gameObjects.add(new greenOrc(730, 275));
            GlobalVariables.gameObjects.add(new Coin(930, 236));
            GlobalVariables.gameObjects.add(new Coin(960, 236));
            GlobalVariables.gameObjects.add(new Coin(990, 236));
            GlobalVariables.gameObjects.add(new bigPlatform(555, 224));
            GlobalVariables.gameObjects.add(new redOrc(1226, 182-100));
            GlobalVariables.gameObjects.add(new smallPlatform(1176, 182));
            GlobalVariables.gameObjects.add(new greenOrc(1628, 292+19));
            GlobalVariables.gameObjects.add(new mediumPlatform(1477, 211+19));
            GlobalVariables.gameObjects.add(new redOrc(1816+50, 204-100));
            GlobalVariables.gameObjects.add(new smallPlatform(1816, 204));
            GlobalVariables.gameObjects.add(new coinChest(2124, 239, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new smallPlatform(2096, 242));
            GlobalVariables.gameObjects.add(new greenOrc(2518, 276));
            GlobalVariables.gameObjects.add(new mediumPlatform(2402, 194));
            GlobalVariables.gameObjects.add(new greenOrc(2902, 384-20));
            GlobalVariables.gameObjects.add(new mediumPlatform(2748, 302-20));
            GlobalVariables.gameObjects.add(new redOrc(3115+50, 271-100));
            GlobalVariables.gameObjects.add(new smallPlatform(3115, 271));
            GlobalVariables.gameObjects.add(new redOrc(3567, 296));
            GlobalVariables.gameObjects.add(new smallPlatform(3431, 230));
            GlobalVariables.gameObjects.add(new weaponChest(3759, 207-9, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new smallPlatform(3728, 209-9));
            GlobalVariables.gameObjects.add(new greenOrc(4221, 322+20));
            GlobalVariables.gameObjects.add(new redOrc(4378, 322-100+20));
            GlobalVariables.gameObjects.add(new Coin(4033+30, 267+12+20));
            GlobalVariables.gameObjects.add(new Coin(4033+60, 267+12+20));
            GlobalVariables.gameObjects.add(new Coin(4033+90, 267+12+20));
            GlobalVariables.gameObjects.add(new bigPlatform(4033, 267+20));
            GlobalVariables.gameObjects.add(new greenOrc(4823, 311+20));
            GlobalVariables.gameObjects.add(new mediumPlatform(4657, 230+20));
            GlobalVariables.gameObjects.add(new greenOrc(5124, 350));
            GlobalVariables.gameObjects.add(new smallPlatform(4983, 284));
            GlobalVariables.gameObjects.add(new greenOrc(5374, 309));
            GlobalVariables.gameObjects.add(new smallPlatform(5233, 244));
            GlobalVariables.gameObjects.add(new redOrc(5499+50, 206-100));
            GlobalVariables.gameObjects.add(new smallPlatform(5499, 206));
            GlobalVariables.gameObjects.add(new coinChest(5785, 348, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new smallPlatform(5767, 348));
            GlobalVariables.gameObjects.add(new greenOrc(6216, 364));
            GlobalVariables.gameObjects.add(new redOrc(6443, 364));
            GlobalVariables.gameObjects.add(new redOrc(6066+300, 310-100));
            GlobalVariables.gameObjects.add(new Coin(6066+30, 310+12));
            GlobalVariables.gameObjects.add(new Coin(6066+60, 310+12));
            GlobalVariables.gameObjects.add(new Coin(6066+90, 310+12));
            GlobalVariables.gameObjects.add(new bigPlatform(6066, 310));
            GlobalVariables.gameObjects.add(new greenOrc(6723, 317));
            GlobalVariables.gameObjects.add(new weaponChest(6778, 247, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new mediumPlatform(6666, 235));
            GlobalVariables.gameObjects.add(new redOrc(7154, 300));
            GlobalVariables.gameObjects.add(new mediumPlatform(6999, 218));
            GlobalVariables.gameObjects.add(new smallPlatform(7311, 316));
            GlobalVariables.gameObjects.add(new redOrc(7628, 355));
            GlobalVariables.gameObjects.add(new redOrc(7728, 355));
            GlobalVariables.gameObjects.add(new smallPlatform(7544, 289));
            GlobalVariables.gameObjects.add(new redOrc(7974, 331));
            GlobalVariables.gameObjects.add(new mediumPlatform(7808, 249));
            GlobalVariables.gameObjects.add(new TNT(8271, 314));
            GlobalVariables.gameObjects.add(new redOrc(8441, 324));
            GlobalVariables.gameObjects.add(new coinChest(8443, 257, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new redOrc(8576, 324));
            GlobalVariables.gameObjects.add(new Coin(8148+30, 269+12));
            GlobalVariables.gameObjects.add(new Coin(8148+60, 269+12));
            GlobalVariables.gameObjects.add(new Coin(8148+90, 269+12));
            GlobalVariables.gameObjects.add(new Coin(8148+30, 269-18));
            GlobalVariables.gameObjects.add(new Coin(8148+60, 269-18));
            GlobalVariables.gameObjects.add(new Coin(8148+90, 269-18));
            GlobalVariables.gameObjects.add(new bigPlatform(8148, 269));
            GlobalVariables.gameObjects.add(new smallPlatform(8723, 217));
            GlobalVariables.gameObjects.add(new redOrc(8957+50, 284-100));
            GlobalVariables.gameObjects.add(new smallPlatform(8957, 284));
            GlobalVariables.gameObjects.add(new mediumPlatform(9377, 272));
            GlobalVariables.gameObjects.add(new redOrc(9831, 314));
            GlobalVariables.gameObjects.add(new smallPlatform(9682, 248));
            GlobalVariables.gameObjects.add(new redOrc(10077, 283));
            GlobalVariables.gameObjects.add(new smallPlatform(9930, 216));
            GlobalVariables.gameObjects.add(new weaponChest(10230, 183, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new smallPlatform(10202, 184));
            GlobalVariables.gameObjects.add(new TNT(10501, 357));
            GlobalVariables.gameObjects.add(new redOrc(10834, 370));
            GlobalVariables.gameObjects.add(new TNT(10926, 357));
            GlobalVariables.gameObjects.add(new Coin(10495+30, 314+12));
            GlobalVariables.gameObjects.add(new Coin(10495+60, 314+12));
            GlobalVariables.gameObjects.add(new Coin(10495+90, 314+12));
            GlobalVariables.gameObjects.add(new Coin(10495+30, 314-18));
            GlobalVariables.gameObjects.add(new Coin(10495+60, 314-18));
            GlobalVariables.gameObjects.add(new Coin(10495+90, 314-18));
            GlobalVariables.gameObjects.add(new bigPlatform(10495, 314));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 696, 346 -100));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 552, 280));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 936, 327 -100));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 782, 263));
            GlobalVariables.gameObjects.add(new coinChest(sceneChanger + 1036, 232, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 1173, 294 -100));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 1028, 230));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 1421, 271 -100));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 1279, 204));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 1673, 238 -100));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 1525, 172));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 1939, 206 -100));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 1795, 141));
            GlobalVariables.gameObjects.add(new weaponChest(sceneChanger + 1981, 394, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 2196, 461));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 2000, 380));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 2528, 422));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 2328, 341));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 2626, 321));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 3037, 355));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 2882, 290));
            GlobalVariables.gameObjects.add(new TNT(sceneChanger + 3215, 396));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 3135, 343));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 3449, 359));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 3374, 293));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 3803, 325));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 3904, 325));
            GlobalVariables.gameObjects.add(new redOrc(sceneChanger + 4014, 325));
            GlobalVariables.gameObjects.add(new TNT(sceneChanger + 4102, 311));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+30, 269+12));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+60, 269+12));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+90, 269+12));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+30, 269-18));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+60, 269-18));
            GlobalVariables.gameObjects.add(new Coin(sceneChanger + 3650+90, 269-18));
            GlobalVariables.gameObjects.add(new bigPlatform(sceneChanger + 3650, 269));
            GlobalVariables.gameObjects.add(new weaponChest(sceneChanger + 4262, 298, random.nextInt(2)));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 4220, 282));
            GlobalVariables.gameObjects.add(new coinChest(sceneChanger + 4575, 271, random.nextInt(11) + 5));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 4530, 256));
            GlobalVariables.gameObjects.add(new smallPlatform(sceneChanger + 4925, 266));
            //boss lvl
            GlobalVariables.gameObjects.add(new bossOrc(sceneChanger + 5498, 223));
            GlobalVariables.gameObjects.add(new bigPlatform(sceneChanger + 5231, 275));
            GlobalVariables.gameObjects.add(new mediumPlatform(sceneChanger + 5693, 249));
            GlobalVariables.gameObjects.add(new bigPlatform(sceneChanger + 5876, 275));
            GlobalVariables.gameObjects.add(new bigPlatform(sceneChanger + 6500, 260));
        }
    }

    public static void addPrincess(AnchorPane gameAnchorPane, double location) {
        princess.setLayoutX(location);
        gameAnchorPane.getChildren().add(princess);
        Animations.translateTransition(princess, 0, -100, 1000, TranslateTransition.INDEFINITE, true).play();
    }
}
